apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: voting-app
    name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-pod
      app: voting-app

  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres-pod
        app: voting-app
    spec:
      containers:
        - name: postgres
          image: postgres:9.4
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name:  POSTGRES_PASSWORD
              value: "postgres"
          ports:
            - containerPort: 5432

